### ISSUE TITLE
Alternative and unusual units

### ISSUE THREAD

**Issue by jsta** [ropenscilabs/convertr#12]
I was considering submitting a PR to add unusual units to `convertr` such as `"basketball court"` and `"american football field"`. Would this be welcome?

**Comment by jsta** [comment]
For example,

| name | quantity_type | catalog_name | catalog_symbol | rp66_symbol | base_unit | a | b | c | d |
|---:|---:|----:|----:|--:|--:|--:|--:|--:|--:|
| american football field | length | Wikipedia |m|m|m |0|110|1|0|

**Comment by GShotwell** [comment]
The `catelog_symbol` needs to be unique for each unit, so can you change it to something like `"Football Field, length (US)"`. Also  good to have "length" in the name so that there could be football field area and width if that ever comes up.

**Comment by GShotwell** [comment]
Sure! Just make sure you include the source of the units.

**Comment by jsta** [comment]
Should I be running `data-raw/data_cleaning.R` afterwards? My additions have unique `catalog_symbol` but I am getting an error that:
> Error: catalog symbols not unique

**Comment by jsta** [comment]
I think the problem is that `readr::read_csv` is treating semicolons as delimeters:
```r
conversion_table <- read_csv("data-raw/conv.csv")
conversion_table[duplicated(conversion_table$catalog_symbol),]
```
```r
1  cubic foot of atmosphere standard cubic foot       energy      Wikipedia
2  cubic yard of atmosphere standard cubic yard       energy      Wikipedia
3          dram (apothecary               troy)         mass      Wikipedia
4           chain (gunter's         surveyor's)       length      Wikipedia
5            link (gunter's         surveyor's)       length      Wikipedia
6           link (ramsden's         engineer's)       length      Wikipedia
7                    x unit            siegbahn       length      Wikipedia
8              circular mil       circular thou         area      Wikipedia
9                square mil         square thou         area      Wikipedia
10                  quarter                pail       volume      Wikipedia
11          fluid dram (us)         us fluidram       volume      Wikipedia
12          gill (imperial)              noggin       volume      Wikipedia
13                   pottle            quartern       volume      Wikipedia
14          sack (imperial)                 bag       volume      Wikipedia
15                arcminute                 moa        angle      Wikipedia
```

**Comment by GShotwell** [comment]
Hmmm, there might be a problem with the `data-raw/data_cleaning.R` script. Maybe do you want to just do a PR with the `.csv` file and I'll fix the data cleaning script on the same branch?

**Comment by jsta** [comment]
Nvm about that, I was using libreoffice to edit the csv and it seems responsible because I am not getting the same error on the original. Trying comma chameleon instead.

**Comment by jsta** [comment]
Do these need to be absolutely official? I was disappointed to learn from Wikipedia that:

> An Olympic-size swimming pool is used as a colloquial unit of volume, to make approximate comparisons to similarly sized objects or volumes. It is not a specific definition, as there is no official limit on the depth of an Olympic pool.

**Comment by GShotwell** [comment]
I think I'd prefer that there be some kind of consensus on the exact
amount. So maybe if there's not some body defining the unit we should leave
it out.

**Comment by jsta** [comment]
This is a gold-mine https://en.wikipedia.org/wiki/List_of_unusual_units_of_measurement
